version: "2"
services:
  mysql-db:
    image: cytopia/mariadb-5.5
    container_name: mysql_container
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always